### PR TITLE
Fixes issue #120 by removing redundant ad call.

### LINKED ISSUE #120: AdError appears after ad finishes
After playing a preroll (skippable or unskippable), an AdError toast message appears as content starts.

### PR DESCRIPTION
**Pull request by ypavlotsky**
Fixes #120

### CODE REVIEW

**Comment by ypavlotsky** [comment]
PTAL

**Comment by shawnbuso** [comment]
LGTM

File: demo/src/main/java/com/google/googlemediaframeworkdemo/demo/adplayer/ImaPlayer.java [hunk 1]
```diff
@@ -396,12 +396,6 @@ public ImaPlayer(Activity activity,
         autoplay);
 
     contentPlayer.addPlaybackListener(contentPlaybackListener);
-    contentPlayer.setPlayCallback(new PlaybackControlLayer.PlayCallback() {
-      @Override
-      public void onPlay() {
```
Comment (SecretRose7) [inline demo/src/main/java/com/google/googlemediaframeworkdemo/demo/adplayer/ImaPlayer.java:401]: open_public_( no private )
